services:
  dlarr:
    image: ghcr.io/ofernander/dlarr:latest
    container_name: dlarr
    hostname: dlarr
    restart: unless-stopped
    ports:
      - "8800:8800"
    volumes:
      - ./data:/config
      - /path/on/host/downloads:/downloads
    environment:
      - TZ=UTC
      - DLARR_WEB_PORT=8800
      - DLARR_LOG_LEVEL=info 
      - DLARR_SSH_HOST=seedbox_address_url
      - DLARR_SSH_PORT=22
      - DLARR_SSH_USER=your_user
      - DLARR_SSH_USE_KEY=true
      # - DLARR_REMOTE_SCAN_SCRIPT_PATH=/tmp/dlarr_scan.py
      # - DLARR_SSH_KEY_PATH=/path/to/custom/key 
      # - DLARR_SSH_PASSWORD=your_password

      # - DLARR_RADARR_1_NAME=radarr-main
      # - DLARR_RADARR_1_URL=http://radarr:7878
      # - DLARR_RADARR_1_API_KEY=<api key>
      # - DLARR_RADARR_1_DIR=/movies <-- This is your local path same as "Remote mappings in *arr instance"

      # - DLARR_SONARR_1_NAME=sonarr-main
      # - DLARR_SONARR_1_URL=http://sonarr:8989
      # - DLARR_SONARR_1_API_KEY=<api key>
      # - DLARR_SONARR_1_DIR=/tv

      # - DLARR_LIDARR_1_NAME=lidarr-main
      # - DLARR_LIDARR_1_URL=http://lidarr:8686
      # - DLARR_LIDARR_1_API_KEY=<api key>
      # - DLARR_LIDARR_1_DIR=/music
